server:
  port: 8081

spring:
  application:
  name: user-mgmt

# MongoDB config
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user-mgmt
      
#Security
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 24h in millisecond
    expiration-time: 86400000
